[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
    "supabase>=2.17.0",
    "trafilatura>=2.0.0",
]
